export type ErrorType = 'EDIT_ACCOUNT_FAILED' | 'CREATE_PORTFOLIO_FAILED' | 'BUY_QUOTE_FAILED' | 'SELL_QUOTE_FAILED';

export const enum ErrorTypeEnum {
  EDIT_ACCOUNT_FAILED = 'EDIT_ACCOUNT_FAILED',
  CREATE_PORTFOLIO_FAILED = 'CREATE_PORTFOLIO_FAILED',
  BUY_QUOTE_FAILED = 'BUY_QUOTE_FAILED',
  SELL_QUOTE_FAILED = 'SELL_QUOTE_FAILED'
}
