export type EventType =
  | 'ACCOUNT_LOADED'
  | 'EMAIL_CHANGED'
  | 'PASSWORD_CHANGED'
  | 'ACCOUNT_EDITED'
  | 'PORTFOLIO_CREATED'
  | 'PORTFOLIO_DELETED'
  | 'QUOTE_BOUGHT'
  | 'QUOTE_SOLD';

export enum EventTypeEnum {
  ACCOUNT_LOADED = 'ACCOUNT_LOADED',
  ACCOUNT_EDITED = 'ACCOUNT_EDITED',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PORTFOLIO_CREATED = 'PORTFOLIO_CREATED',
  PORTFOLIO_DELETED = 'PORTFOLIO_DELETED',
  QUOTE_BOUGHT = 'QUOTE_BOUGHT',
  QUOTE_SOLD = 'QUOTE_SOLD'
}
