version: '3.8'
services:
  db:
    build:
      context: services/db
      dockerfile: Dockerfile.development
    ports:
      - 5300:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=invest_sandbox
      - POSTGRES_PASSWORD=1234
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/invest_sandbox
    image: 'invest_sandbox'
    ports:
      - 8091:8091
    depends_on:
      - db

  nginx:
    image: nginx:1.19.10-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:8989

  angular:
    build:
      context: ../investsandbox-frontend
      dockerfile: Dockerfile.development
    ports:
      - 4200:4200
    depends_on:
      - nginx

volumes:
  db-data: