version: '3.8'
services:
  db:
    build:
      context: services/db
      dockerfile: Dockerfile.development
    ports:
      - 5300:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=invest_sandbox
      - POSTGRES_PASSWORD=1234
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/invest_sandbox
    image: 'invest_sandbox'
    ports:
      - 80:8091
    depends_on:
      - db

volumes:
  db-data: